### ISSUE TITLE
Add Content and ContentType model

### ISSUE THREAD

**Issue by mykeels** [college-portal/college-portal#17]
# Models

Similar to the [Image](https://github.com/college-portal/college-portal/blob/edge/app/Models/Image.php) and [ImageType](https://github.com/college-portal/college-portal/blob/edge/app/Models/ImageType.php) models, we need one for content, which are extra information that models have, that are not captured in the table.

## Action Plan

- [x] Create `ContentType` model

  - school_id
  - type
  - name
  - related_to (numeric, FK to ContentType)
  - created_at
  - updated_at

- [x] Create `Content` model

  - owner_id
  - content_type_id
  - value (string)
  - created_at
  - updated_at

# Migrations

Create migration scripts for the `contents` and `content_types` tables, just like seen in these migration files:

- [create_image_types_table](https://github.com/college-portal/college-portal/blob/edge/database/migrations/2018_07_01_154333_create_image_types_table.php)
- [rel_image_types](https://github.com/college-portal/college-portal/blob/edge/database/migrations/2018_07_02_100829_rel_image_types.php)
- [create_images_table](https://github.com/college-portal/college-portal/blob/edge/database/migrations/2018_07_01_154343_create_images_table.php)
- [rel_images](https://github.com/college-portal/college-portal/blob/edge/database/migrations/2018_07_02_100836_rel_images.php)

## Action Plan

So four migration scripts will be expected with names ending with:

- [x] create_content_types_tables
- [x] rel_content_types
- [x] create_contents_tables
- [x] rel_contents_types

in that order

**Comment by jcobhams** [comment]
More info/context please

**Comment by mykeels** [comment]
Done! @jcobhams

**Comment by thecodearcher** [comment]
@mykeels I will work on this before the end of today

**Comment by mykeels** [comment]
Thanks, @thecodearcher!
