### ISSUE TITLE
Add Asset and AssetType model

### ISSUE THREAD

**Issue by mykeels** [college-portal/college-portal#28]
# Models

Similar to the [Image](https://github.com/college-portal/college-portal/blob/edge/app/Models/Image.php) and [ImageType](https://github.com/college-portal/college-portal/blob/edge/app/Models/ImageType.php) models, we need one for assets, which are files that are not images like PDFs, Excel, etc.

## Action Plan

- [x] Create `AssetType` model

  - school_id
  - type
  - name
  - created_at
  - updated_at

- [x] Create `Asset` model

  - owner_id
  - asset_type_id
  - location
  - mime
  - size (in bytes)
  - created_at
  - updated_at

# Migrations

Create Migrations for the `assets` and `asset_types` tables, just like seen in these migration files:

- [create_image_types_table](https://github.com/college-portal/college-portal/blob/edge/database/migrations/2018_07_01_154333_create_image_types_table.php)
- [rel_image_types](https://github.com/college-portal/college-portal/blob/edge/database/migrations/2018_07_02_100829_rel_image_types.php)
- [create_images_table](https://github.com/college-portal/college-portal/blob/edge/database/migrations/2018_07_01_154343_create_images_table.php)
- [rel_images](https://github.com/college-portal/college-portal/blob/edge/database/migrations/2018_07_02_100836_rel_images.php)

## Action Plan

So four migration scripts will be expected with names ending with:

- [x] create_asset_types_tables
- [x] rel_asset_types
- [x] create_assets_tables
- [x] rel_asset_types

**Comment by Temidayojnr** [comment]
Okay, I'll update you on this once it's done.

**Comment by jcobhams** [comment]
Just a thought, why don't we collapse the `Image` and `ImageType` models into Assets. 

Aren't images technically a type of `Asset`

@mykeels ☝️

**Comment by mykeels** [comment]
Yea, that's something we can do in the future @jcobhams ... Thanks for working on this, @Temidayojnr !
